#%RAML 1.0 DataType

type: object

properties:
  reqId:
    type: integer
  requestorId:
    type: integer
  envName:
    type: string
  envId:
    type: string
  orgId:
    type: string
  deploymentId:
    type: string
  loggingActivity:
    type: string
  envType:
    type: string
  userType:
    type: string
  a_dId:
    type: integer
  reqStatus:
    type: string
  teamId:
    type: string
  teamName:
    type: string
  